version: '3.3'

networks:
  hadoop-swarm:
    driver: overlay

services:

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - hadoop-swarm
    depends_on:
      - hadoop-master


  hadoop-master:
    image: "${HOST_IP}:5000/hadoop" # We need to host a private repository
    tty: true
    deploy:
      replicas: 1
    networks:
      - hadoop-swarm
    ports:
      - "8088:8088"
      - "50070:50070"
      - "9000:9000"


  hadoop-slaves:
    image: "${HOST_IP}:5000/hadoop"
    tty: true # Allows bash to execute, thus keeping container up & running
    deploy:
      replicas: 3
    networks:
      - hadoop-swarm
    depends_on:
      - hadoop-master
